### ISSUE TITLE
Discussion thread for http API design

### ISSUE THREAD

**Issue by jdoliner** [pachyderm/pfs#18]
Currently the API exposes 3 endpoints:

- `/file`
- `/commit`
- `/branch`

They all behave somewhat similarly in that they use `POST`/`PUT` for creation, `GET` for access and `DELETE` for deletion (although `/commit` and `/branch` currently don't support deletion).

However they don't all refer to objects the same way. For example:

```shell
# creating a file called foo
curl -XPUT pfs/file/foo -d @foo
# creating a branch called foo
curl -XPOST pfs/branch?commit=<commit>&branch=foo
```

Our scheme right now does have one pretty nice feature which is that objects of the same type always occur in the same place. Filenames are always part of the URL. Branches are always the `branch` parameter etc. However this seems like it might be a local maxima design wise.

**Comment by KrishnaPG** [comment]
Looks interesting. It would be great if compatibility is kept between git's http access syntax and the proposed file access syntax. For example, git's way of accessing the ReadMe.md at `master' and `some old version` is
````
    https://github.com/pachyderm/pfs/blob/master/README.md
    https://github.com/pachyderm/pfs/blob/90fcb0f0d8ab233daf2449c1125c5e6f7bee0d2d/README.md
````
Essentially it is following the `<root>/<branch>/<filename>` pattern.

Since the syntax we select for the access API is going to effect the performance and other factors it may be better to evaluate all the options w.r.to some of the below factors.

Few important factors to that comes to my mind to consider for evaluation are:
    + `subscribers` or `listeners` for any modifications at any level of the file system tree.
    + security / access control
    + Throttling / Rate limiting
    + Caching / invalidating

Most of these above are common for all file-systems since old ages - what is the need of hour and expected desperately from new file systems is:
    + ability to join and remove additional file systems on the fly (e.g. files mapped on smart phones' SD card being able to join and remove as user walks across wifi zones). The key is: being able to serve files from the near-by smart phone's SD card on wifi, rather than going through central server from remote location  (similar to bit-torrent), and fall back to central server when the phone is not available.
