### ISSUE TITLE
Job output error

### ISSUE THREAD

**Issue by Dal-Papa** [pachyderm/pfs#36]
Hello guys,

Firstly congrats for this idea, it's brilliant !
Then, I started using it, and tried to deploy a small PFS on AWS CloudFormation, doing my Docker container and stuff and do a Job.

When I try to get the result, here is what I get : 
```
curl -XGET 127.0.0.1/job/test_map/file/f5e1d55937?commit=a335b6db-4a58-4b79-a414-8c1da269c4ce
Failed request (500 Internal Server Error) to http://ip-172-X-X-X.us-west-2.compute.internal:53442/job/test_map/file/f5e1d55937?commit=a335b6db-4a58-4b79-a414-8c1da269c4ce.
```
It should use 127.0.0.1 but it's using my hostname somehow ... 

Am I doing anything wrong or is it a bug ? 
Cheers,

**Comment by jdoliner** [comment]
Hi!

Glad you like the idea!! Now let's see if we can get it working for you in practice.

Using the hostname is actually expected behavior.
The way that pfs does its routing is that each shard has a sidekick service which runs next to it called the announcer. This service publishes the hostname at which the shard can be found as long as the shard is still alive. That's where the hostname is coming from.

So that's all as it should be, what's not as it should be is that the server is erroring. The fastest way to get to the bottom of this would be to get the logs. The easiest way to grab those would be `fleetctl journal master-0-1` (assuming a 1 shard cluster).

Really sorry you ran in to this. I'll try to get to the bottom if it ASAP.

**Comment by Dal-Papa** [comment]
Hey Joe

Thanks for the quick answer. I have to admit I didn't know about this `journal` part of `fleetctl`. I'm now able to see more log and a lot is coming from my Go server so I think I'll investigate first there and it might work itself out !

I will let you know for sure of my progress.
Thanks again.

**Comment by JoeyZwicker** [comment]
Closing. Feel free to reopen if this is still a problem.
