### ISSUE TITLE
Improve documentation

### ISSUE THREAD

**Issue by neojski** [pachyderm/pfs#46]
In file https://github.com/pachyderm/pfs/blob/master/README.md it wasn't very clear that `pfs` in 

```sh
 curl -XPOST pfs/file/<file>?branch=<branch> -T local_file
```

Means the host full address of the running pachyderm instance (including port number). Of course it is easy to guess that from https://github.com/pachyderm/chess/blob/master/install/pachyderm/local but it might be worth improving.

**Comment by neojski** [comment]
It'd be also very useful to add to `How do I hack on pfs?` section. In particular, I imagine it's possible to `git clone` pachyderm in some special container, modify go code, recompile and restart server and keep using curl for communication.

Right now I just tried cloning this repo, `docker build .` and then modifying `launch` script with the just built image. Highly inefficient.

**Comment by jdoliner** [comment]
Definitely agree on both of these points.

What do you think would make it clear in the first case? My instinct would be `PFS_HOST`, since it makes it clear that we're talking about a hostname and the fact that it's all caps will hopefully indicate that it's not meant literally like the rest of the parts of the path.

As for the second one, what if we had a script `scripts/launch-dev` which builds an image using the contents of the local directory and then runs the launch script with it as the target?

**Comment by jdoliner** [comment]
The PR above contains code which should address this issue.

**Comment by JoeyZwicker** [comment]
We're going to a massive documentation improvement this release cycle.
