### ISSUE TITLE
Simple map-reduce not working

### ISSUE THREAD

**Issue by neojski** [pachyderm/pfs#48]
I wanted to create a simple nodejs map-reduce thingy using pachyderm. It's in my playground repo: https://github.com/neojski/pachyderm-playground. For some reason the reduce part doesn't work. At the
beginning I thought the reason was that I used to have map and reduce in the same container but changing that didn't help.

Unfortunately [chess demo](https://github.com/pachyderm/chess/tree/master/job) doesn't run reduce at all.

I think that a simple working demo with map and reduce would be very useful.

Log below:

```
master.go:290: Listening on port 80...
master.go:291: dataRepo: data-0-1, compRepo: comp-0-1.
master.go:241: URL in job handler:
/job/countMap
master.go:249: URL with reset path:
/file/job/countMap
master.go:241: URL in job handler:
/job/countReduce
master.go:249: URL with reset path:
/file/job/countReduce
shell.go:12: RunStderr:
&{/bin/btrfs [btrfs property set /var/lib/pfs/vol/data-0-1/master ro true] []  <nil> <nil> <nil> [] <nil> <nil> <nil> ?reflect.Value? false [] [] [] [] <nil>}
shell.go:12: RunStderr:
&{/bin/btrfs [btrfs subvolume snapshot /var/lib/pfs/vol/data-0-1/0a624d53-695d-4780-98eb-60b11c9e513c /var/lib/pfs/vol/data-0-1/master] []  <nil> <nil> <nil> [] <nil> <nil> <nil> ?reflect.Value? false [] [] [] [] <nil>}
mapreduce.go:425: Materialize: data-0-1 master 0a624d53-695d-4780-98eb-60b11c9e513c comp-0-1 job.
mapreduce.go:457: Make docker client.
mapreduce.go:476: Jobs: [0xc20801afa0 0xc20801b090]
mapreduce.go:482: Running job:
countMap
mapreduce.go:497: Job: {map count_input neojski/pachyderm-count-map [/bin/map] 5 5 1200}
mapreduce.go:48: spinupContainer neojski/pachyderm-count-map [/bin/map]
mapreduce.go:482: Running job:
countReduce
mapreduce.go:497: Job: {reduce job/countMap neojski/pachyderm-count-reduce [/bin/reduce] 5 5 1200}
mapreduce.go:48: spinupContainer neojski/pachyderm-count-reduce [/bin/reduce]
mapreduce.go:59: starting container
mapreduce.go:59: starting container
mapreduce.go:40: container started
mapreduce.go:329: Reduce: {reduce job/countMap neojski/pachyderm-count-reduce [/bin/reduce] 5 5 1200} countReduce 
mapreduce.go:88: Retrying due to error: Get http://172.17.42.1:4001/v2/keys/pfs/master?quorum=false&recursive=true&sorted=false: dial tcp 172.17.42.1:4001: connection refused
mapreduce.go:40: container started
mapreduce.go:224: book1.txt: Posting: http://172.17.0.4/book1.txt
mapreduce.go:226: book1.txt: Post done.
mapreduce.go:88: Retrying due to error: Post http://172.17.0.4/book1.txt: dial tcp 172.17.0.4:80: connection refused
mapreduce.go:224: book1.txt: Posting: http://172.17.0.4/book1.txt
mapreduce.go:226: book1.txt: Post done.
mapreduce.go:235: book1.txt: Creating file comp-0-1/master/countMap/book1.txt
mapreduce.go:242: book1.txt: Opened outfile.
mapreduce.go:257: book1.txt: Copying output...
mapreduce.go:262: book1.txt: Done copying.
mapreduce.go:263: Result of timer.Stop(): true
mapreduce.go:88: Retrying due to error: Get http://10.1.42.1:4001/v2/keys/pfs/master?quorum=false&recursive=true&sorted=false: dial tcp 10.1.42.1:4001: i/o timeout
```

It might just be the case that map returns wrong value but I don't see any documentation for that.

Also, I think that you should describe how to prepare docker images. I've seen that you mentioned somewhere that they should be http servers. What about ports? Can I have multiple maps (or map + reduce) in one container?

**Comment by jdoliner** [comment]
Hi @neojski I think I know what's going on here, and it's entirely our fault. Reduce is currently broken in single node mode because it requires etcd to be present so it can look up the other nodes. This is sort of silly because there's actually only one node in a single node cluster so it's failing to look up itself.

I'll get this fixed ASAP.

> I think that a simple working demo with map and reduce would be very useful.
100% agree, we'll want to have this in several languages as well so the fact that you're doing this in node is extra awesome.

> Also, I think that you should describe how to prepare docker images. I've seen that you mentioned somewhere that they should be http servers. What about ports? Can I have multiple maps (or map + reduce) in one container?

I'll make sure to get this documented as well. The answers for posterity:
Servers should always listen on port 80.
You can have as many maps and reduces in the same containers as you want. The image name command pair is what defines the behavior of a job. In general storing things in the same container makes sense when they share libraries because it decreases the amount of container data to be pushed around.

**Comment by neojski** [comment]
Ok. Please let me know when it's fixed.

**Comment by jdoliner** [comment]
Alrighty, I just tested this in next and it seems to be working. `git checkout next && scripts/dev-launch` to try it out. Let me know if that works for you.

Also I was able to test this using the job you created because you pushed the image to docker hub but the Dockerfile seems to be missing from the GH repo, probably just a forgotten `git add`. When you have a second would you mind pushing that so others can build the pipeline.

Thanks for your patience with this issue.

**Comment by neojski** [comment]
There's a Dockerfile in both [map](https://github.com/neojski/pachyderm-playground/tree/master/image/map) and [reduce](https://github.com/neojski/pachyderm-playground/tree/master/image/reduce). I'll try to test it later.

**Comment by neojski** [comment]
I updated [my map-reduce](https://github.com/neojski/pachyderm-playground) and now it calculated the total length of all files in data directory.

**Comment by jdoliner** [comment]
> There's a Dockerfile in both map and reduce. I'll try to test it later.

Whoops, I'm blind.

> I updated my map-reduce and now it calculated the total length of all files in data directory.

:+1: Awesomeness. Do you mind if we references this as an example pipeline.


This issue seems resolved, mind if I close?

**Comment by neojski** [comment]
Feel free to reference it :-)

It's resolved but please mention [next](https://github.com/pachyderm/pfs/tree/next) branch on "hacking pfs" section.

Thanks for fixing this.
