### ISSUE TITLE
Too new btrfs

### ISSUE THREAD

**Issue by neojski** [pachyderm/pfs#49]
Is it really necessary to have [btrfs of version `3.14`](https://github.com/pachyderm/pfs/blob/82acd9ac719c0a0a99d81fd942803719d5373302/scripts/launch#L24)? In the docker era this version checking is sooo ugly.

**Comment by jdoliner** [comment]
This is definitely an annoyance that I'd like to have go away. It's a bit tricky though, here's the situation as I understand it, it may well be that there's a better solution that I don't know about.

There are 2 components of btrfs that pfs depends on. There's the btrfs kernel module and there's btrfs-tools which is a normal binary (not a kernel module). Unfortunately kernel modules are one of the few things that Docker doesn't fix, the kernel you see inside a container is the same as the one you see on the host machine and the same image can encounter different kernels and thus different behaviors if it's run on different machines. This is problematic because we need btrfs-tools to match with the kernel module which means btrfs-tools can't be part of the image without seriously limiting the places that the image can run.

We've struggled with this problem for a while and ultimately arrived at the solution of mapping in the host's filesystem so that we can use the btrfs-tools that are installed there. This is definitely a suboptimal solution since it creates a dependency other than Docker but so far it's the best we have. There might be a better solution to this out there, I'm pretty novice at kernel module management.

---

There are a few things we could do to make this better.

- The requirement of 3.14 is probably way to strict, I suspect we could function fine using an older version.

- Supporting multiple backends could help with this. In particular I think an overlayfs backend might wind up being a good default in the long run because it seems like everything we need is in the kernel by default and the API is pretty stable (mostly because it's so simple.)

**Comment by neojski** [comment]
I forgot to add that I have `btrfs-progs v3.19` on my machine. So the above didn't pass because my thing was too new.

It wasn't very difficult to get it on archlinux but I understand that this could be annoying if you have to take care of that kernel dependency on all of your dockerized machines. Thanks for explaining that.

**Comment by jdoliner** [comment]
Ugh that should be fixable in the short term. That's just bad version checking. Sorry about that, I'll get this fixed.

**Comment by DimShadoWWW** [comment]
#67
