### ISSUE TITLE
Problems with examples/WordCount.md

### ISSUE THREAD

**Issue by DazWilkin** [pachyderm/pfs#85]
I understand it in principle.

Getting it to work, not so much!

#### Problem 1: "The data you want to analyze is stored at pfs://data"

This seems a novel way to express the location and I don't see this syntax elsewhere.

I've tried

    curl -XPOST localhost/data/shakespeare

and

    curl -XPOST localhost/file/data/shakespeare

It's unclear whether there's a need|command to create directories. Or indeed whether this is what "pfs://data" represents.

#### Problem 2: I don't get what I expect from wildcard listings

...and so can't debug using them.

    curl -XPOST localhost/file/shakespeare -T shakespeare.txt
    curl localhost/file/*

yields

```
--54c0e46d0daa62501c32dcb1192fab024dced5c79694e6fc636e65dbc6b4
Content-Disposition: form-data; name=".meta"; filename=".meta"
Content-Type: application/octet-stream

read /var/lib/pfs/vol/data-0-3/master/.meta: is a directory

--54c0e46d0daa62501c32dcb1192fab024dced5c79694e6fc636e65dbc6b4--
--aacee4ccb8343ee523f6756c9682f72a7921929a985e0c1e860fa976532d
Content-Disposition: form-data; name=".meta"; filename=".meta"
Content-Type: application/octet-stream

read /var/lib/pfs/vol/data-1-3/master/.meta: is a directory

--aacee4ccb8343ee523f6756c9682f72a7921929a985e0c1e860fa976532d--
--b00326203901e2f2349f8d6c7e945c342c85f4957327a9b8bbf418662099
Content-Disposition: form-data; name=".meta"; filename=".meta"
Content-Type: application/octet-stream

read /var/lib/pfs/vol/data-2-3/master/.meta: is a directory

--b00326203901e2f2349f8d6c7e945c342c85f4957327a9b8bbf418662099--
```

#### Problem 3: Installing the pipeline seems too easy to confuse but... ;-)

I either get a 404 which would make sense but not for words like "the".

Or the command blocks (seemingly) indefinitely:

    curl localhost/pipeline/wordcount/file/counts/the?commit=commit03

#### Problem 4: The documentation references jobs

But the Wordcount example appears to be just a Dockerfile spec. Should I be wrapping it in a job?

#### Problem 5: I don't know how to debug

I was expecting to see an additional docker container(s) spun up to run the pipeline but don't.

**Comment by jdoliner** [comment]
Problem 1:
`"pfs://data"` is a confusing way to describe it sorry about that. What we're trying to say is that `data` is a directory in pfs which contains the text to be processed. There's no need to create directories in pfs, they get created when there's files to put in them. You should get the data in the correct spot with:
```
curl -XPOST localhost/file/data/shakespeare -T shakespeare.txt
```

Problem 2:
Wild card listings should return a multipart message containing a part per file that it finds in the filesystem. However they're not doing what they should be doing for you :( they're erroring due to a bug. Sorry about that we'll get it fixed ASAP. I've setup #86 to track progress.

Problem 3:
Requests for the value of a pipeline at a specific commit will block until the pipeline gets run on that commit and the value becomes available. However there's a number of ways that this can go wrong such as if the pipeline crashes. Any chance that you could take a look at one of the log files for your servers? It's a bit annoying right now since you have to ssh to the machine and look at local host. They're locate in `/var/lib/pfs/log` on each of the hosts.

This is definitely a fragile part of Pachyderm that we're going to need cleanup. I've create #87 to track it.

Problem 4:
Jobs are now deprecated in lieu of pipelines. We'll be doing a big purge ASAP.

Problem 5:
You should see some additional docker container(s). This might be silly but did you try `docker ps -a` so you'd see jobs that have already exited? It's also quite possible that something went wrong and the container was never started in which case logs will probably have the answer.

Again thank so so much for putting up with our very raw documentation and telling us how to make it better. :heart:

Shoot me an email at jd@pachyderm.io with your TShirt size and I'll get you some swag.

**Comment by DazWilkin** [comment]
Thank you for being so supportive and apologies for my stupid questions.

Problem 1: OK -- That I guessed correctly at least.

Problem 2: Ack.

Problem 3: I've grabbed the logs and will mail to you.

Problem 4: Ack.

Problem 5: I did not. I suspect I'm creating the job incorrectly. I'll ship my pachfile to you too.

    docker ps -a
```
CONTAINER ID        IMAGE                  COMMAND                CREATED             STATUS              PORTS                   NAMES
c6b460a38609        pachyderm/pfs:latest   "/go/bin/router 3"     10 hours ago        Up 10 hours         0.0.0.0:80->80/tcp      router              
e9ab62c7ede4        pachyderm/pfs:latest   "/go/bin/shard 2-3 p   10 hours ago        Up 10 hours         0.0.0.0:49161->80/tcp   shard-2-3           
9195ad2e5859        pachyderm/pfs:latest   "/go/bin/shard 0-3 p   10 hours ago        Up 10 hours         0.0.0.0:49153->80/tcp   shard-0-3           
a1d6d2c15c56        pachyderm/pfs:latest   "/go/bin/shard 1-3 p   10 hours ago        Up 10 hours         0.0.0.0:49158->80/tcp   shard-1-3   
```

**Comment by peter-edge** [comment]
Fixes for everything here should be complete. Thanks for the help!
